name: Docker Image For Coverage SonarCloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u tuthur9 -p @Mack:261113
    - name: Run the Docker image
      run: docker run tuthur9/sonar-scanner:latest
